{% set name = "types-python-dateutil" %}
{% set version = "2.9.0.20241003" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-python-dateutil-{{ version }}.tar.gz
  sha256: 58cb85449b2a56d6684e41aeefb4c4280631246a0da1a719bdbe6f3fb0317446

build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  requires:
    - pip
  commands:
    - python -m pip check
    - test -f $SP_DIR/dateutil-stubs/__init__.pyi  # [not win]
    - if not exist %SP_DIR%\\ateutil-stubs\\__init__.pyi exit 1  # [win] 


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for python-dateutil
  description: |
    This is a PEP 561 type stub package for the python-dateutil package. 
    It can be used by type-checking tools like mypy, pyright, pytype, 
    PyCharm, etc. to check code that uses python-dateutil.
  license: Apache-2.0 AND MIT
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/python/typeshed/tree/main/stubs/python-dateutil
  doc_url: https://github.com/python/typeshed/blob/main/README.md

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
