{% set name = "types-python-dateutil" %}
{% set version = "2.8.19.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-python-dateutil-{{ version }}.tar.gz
  sha256: d642f7af2bb99fe78f5a776fd0ca4e32932720047f400e25ad62bc2a5b18dc94

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/dateutil-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for python-dateutil
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
